version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      # AWS ECRログイン
      # - echo Logging in to Amazon ECR....
      # - aws --version
      # - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
      # List all files to debug
      - echo "ファイルリストアップ..."
      - ls -la
      # npmパッケージのインストール
      - echo "依存パッケージのインストールを開始します..."
      - npm install
      # イメージ情報
      - echo "イメージ情報宣言..."
      - IMAGE_REPO_WEB=demo/demo-nextjs
      - REPOSITORY_URI=public.ecr.aws/n5r1w0t7/demo/demo-nextjs
      - IMAGE_URI_WEB=$REPOSITORY_URI/$IMAGE_REPO_WEB
      - IMAGE_TAG=$(echo $CODEBUILD_BUILD_ID | md5sum | cut -d' ' -f1)

  build:
    commands:
      # アプリケーションのビルドを実行
      - echo "ビルドを開始します..."
      - npm run build
      # テストの実行（CIモード、カバレッジ収集）
      - echo "ユニットテスト（カバレッジとJUnitレポート付き）を実行します..."
      - npm run test -- --ci --coverage
      # イメージ作成
      # - echo "Dockerイメージビルド..."
      # - docker build --platform linux/amd64 -t $IMAGE_REPO_WEB:latest . --no-cache
      # - docker tag $IMAGE_REPO_WEB:latest $IMAGE_URI_WEB:$IMAGE_TAG

  post_build:
    commands:
        # ECRへイメージプッシュ
        - echo "Pushing the Docker image..."
        # - docker image ls -a
        # - docker push $IMAGE_URI_WEB:$IMAGE_TAG

artifacts:
  files:
    - "**/*"          # out/ディレクトリ内のすべてのファイルとフォルダを含む
  base-directory: out  # artifactsとして保存するベースディレクトリを指定
  discard-paths: no    # フォルダ構造を保持する設定

reports:
  jest-junit-report:
    files:
      - junit.xml      # JUnit形式のテスト結果ファイル
    base-directory: test-results
    file-format: JunitXml