version: 2.1

executors:
  node-executor:
    docker:
    - image: cimg/node:23.11.0
    working_directory: ~/app

jobs:
  build:
    executor: node-executor
    steps:
    # Pull code from Github repo
    - checkout

    # Install lib
    - run:
        name: Install Dependencies
        command: npm install

    # Check error ESLint
    - run:
        name: Lint code
        command: npm run lint

    # Check code error format TypeScript
    - run:
        name: Lint code
        command: npm run type-check

    # Run test
    - run:
        name: Run Tests
        command: npm test

    # Export report
    - store_test_results:
        path: test-results

    - store_artifacts:
        path: test-results
        destination: test-report
    # - run:
    #     name: Build Next.js
    #     command: npm run build

workflows:
  build-and-test-for-Frontend:
    jobs:
    - build
