version: 2.1

executors:
  node-executor:
    docker:
    - image: cimg/node:23.11.0
    working_directory: ~/app

jobs:
  build:
    executor: node-executor
    steps:
    - checkout

    - run:
        name: Install Dependencies
        command: npm install

    - run:
        name: Lint code
        command: npm run lint

    - run:
        name: Run Tests
        command: npm test

    - store_test_results:
        path: test-results

    - store_artifacts:
        path: test-results
        destination: test-report
    # - run:
    #     name: Build Next.js
    #     command: npm run build

workflows:
  version: 2
  build-and-test-for-Frontend:
    jobs:
    - build
